// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationSys_LaMaisonRestaurant.Data;

#nullable disable

namespace ReservationSys_LaMaisonRestaurant.Migrations
{
    [DbContext(typeof(ReservationSys_LaMaisonRestaurantContext))]
    [Migration("20260314152127_RestaurantInfo")]
    partial class RestaurantInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationSys_LaMaisonRestaurant.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivateDining")
                        .HasColumnType("bit");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Reservation");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ReservationSys_LaMaisonRestaurant.Models.RestaurantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ClosingHours")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningHours")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ReservationSlotIncrements")
                        .HasColumnType("time");

                    b.Property<int>("TotalGuestsPerSlot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RestaurantInfo");
                });

            modelBuilder.Entity("ReservationSys_LaMaisonRestaurant.Models.RestaurantState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RestaurantState");
                });

            modelBuilder.Entity("ReservationSys_LaMaisonRestaurant.Models.RestaurantInfo", b =>
                {
                    b.OwnsOne("ReservationSys_LaMaisonRestaurant.Models.ExtraInfo", "ExtraInfo", b1 =>
                        {
                            b1.Property<int>("RestaurantInfoId")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("PrivateDiningStartTime")
                                .HasColumnType("time");

                            b1.HasKey("RestaurantInfoId");

                            b1.ToTable("RestaurantInfo");

                            b1.ToJson("ExtraInfo");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantInfoId");
                        });

                    b.Navigation("ExtraInfo");
                });

            modelBuilder.Entity("ReservationSys_LaMaisonRestaurant.Models.RestaurantState", b =>
                {
                    b.OwnsMany("ReservationSys_LaMaisonRestaurant.Models.TimeSlotOccupancy", "OccupancyPerTimeSlot", b1 =>
                        {
                            b1.Property<int>("RestaurantStateId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("PartySizeSum")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("TimeSlot")
                                .HasColumnType("time");

                            b1.HasKey("RestaurantStateId", "Id");

                            b1.ToTable("RestaurantState");

                            b1.ToJson("OccupancyPerTimeSlot");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantStateId");
                        });

                    b.Navigation("OccupancyPerTimeSlot");
                });
#pragma warning restore 612, 618
        }
    }
}
